on:
  push:
    branches:
      - main
name: Build and Deploy on AWS
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create back-end env file
        uses: SpicyPizza/create-envfile@v1.3.1
        with:
          envkey_PORT: ${{secrets.PORT}}
          envkey_POSTGRES_USERNAME: ${{secrets.POSTGRES_USERNAME}}
          envkey_POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          envkey_POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          envkey_DATABASE_URL: ${{secrets.DATABASE_URL}}
          directory: back-end
          file_name: .env
          fail_on_empty: true
      - name: Create front-end env file
        uses: SpicyPizza/create-envfile@v1.3.1
        with:
          envkey_REACT_APP_BACK_END_URL: ${{secrets.REACT_APP_BACK_END_URL}}
          directory: front-end
          file_name: .env
          fail_on_empty: true
      - name: Run docker compose down
        run: docker compose down
      - name: Delete react docker volume
        run: docker volume rm gerador-pessoas-fullstack-docker_react-volume
      - name: Build docker images
        run: docker compose build
      - name: Run docker compose up
        run: docker compose up -d